Add show of comparators as IFs
Naty-S/TAC pull request #5
Opened 2020-01-31 00:56 UTC by gustavoaca1997

2020-01-31 00:58 UTC, aitorres approved these changes

2020-02-01 23:09 UTC, Naty-S approved these changes

2020-02-01 23:10 UTC, Naty-S requested changes
Que tal si le quitamos el `then` y se queda solo como `goto` para simplificarlo?

2020-02-02 23:44 UTC, ShonTitor approved these changes

2020-02-04 17:19 UTC, german1608 approved these changes

2020-02-05 14:14 UTC, merged