add show implementation for labels
Naty-S/TAC pull request #6
Opened 2020-02-05 14:32 UTC by german1608

2020-02-05 15:59 UTC, gustavoaca1997 commented
aprobado

2020-02-07 05:02 UTC, aitorres approved these changes

2020-02-10 19:05 UTC, gustavoaca1997 approved these changes

2020-02-10 19:17 UTC, gustavoaca1997 reviewed
¿No sería mejor solo `show label ++ ":"`?

2020-02-10 23:14 UTC, Naty-S requested changes
Opino igual que Gustavo. Así es mas sencillo

2020-02-10 23:47 UTC, Naty-S approved these changes

2020-02-11 12:34 UTC, ShonTitor approved these changes

2020-02-11 13:29 UTC, merged